import json
import os

files = {
    r'c:\proj\payme\lib\l10n\app_en.arb': {
        "billTo": "BILL TO",
        "generatedBy": "Generated by PayMe",
        "page": "Page",
        "ofWord": "of",
        "documentTitle": "Document Title",
        "documentLayout": "Document Layout",
        "layoutStandard": "Standard",
        "layoutDuplicate": "Duplicate",
        "printing": "Printing",
        "data": "Data",
        "security": "Security",
        "business": "Business",
        "localization": "Localization",
        "syncRequired": "Synchronizing..."
    },
    r'c:\proj\payme\lib\l10n\app_fr.arb': {
        "billTo": "FACTURER À",
        "generatedBy": "Généré par PayMe",
        "page": "Page",
        "ofWord": "sur",
        "documentTitle": "Titre du document",
        "documentLayout": "Mise en page du document",
        "layoutStandard": "Standard",
        "layoutDuplicate": "Duplicata",
        "printing": "Impression",
        "data": "Données",
        "security": "Sécurité",
        "business": "Entreprise",
        "localization": "Localisation",
        "syncRequired": "Synchronisation en cours..."
    },
    r'c:\proj\payme\lib\l10n\app_ar.arb': {
        "billTo": "فاتورة إلى",
        "generatedBy": "تم الإنشاء بواسطة PayMe",
        "page": "صفحة",
        "ofWord": "من",
        "documentTitle": "عنوان المستند",
        "documentLayout": "تخطيط المستند",
        "layoutStandard": "قياسي",
        "layoutDuplicate": "نسخة مكررة",
        "printing": "طباعة",
        "data": "البيانات",
        "security": "الأمان",
        "business": "الشركة",
        "localization": "اللغة والمنطقة",
        "syncRequired": "جاري المزامنة..."
    }
}

for path, new_keys in files.items():
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    data.update(new_keys)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {path}")
