import os, re

# 1. Fix repository_providers.dart import
file_path = r'c:\proj\payme\lib\presentation\providers\repository_providers.dart'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace("import 'package:flutter_gen/gen_l10n/app_localizations.dart';", "import '../../l10n/app_localizations.dart';")
with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

# 2. Fix pdf_generation_service.dart
file_path = r'c:\proj\payme\lib\services\pdf_generation_service.dart'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace('style: pw.BorderStyle.dashed', 'borderStyle: pw.BorderStyle.dashed')
with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

# 3. Fix pdf_generation_service_test.dart
file_path = r'c:\proj\payme\test\services\pdf_generation_service_test.dart'
if os.path.exists(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    if 'class FakePdfLocalizations' not in content:
        fake_class = '''
import 'package:payme/core/pdf/pdf_localizations.dart';
class FakePdfLocalizations implements PdfLocalizations {
  @override String get billTo => 'BILL TO';
  @override String get description => 'Description';
  @override String get notes => 'Notes';
  @override String get generatedBy => 'Generated by PayMe';
  @override String get page => 'Page';
  @override String get of => 'of';
  @override String get totalInvoiced => 'Total Invoiced';
  @override String get totalPaid => 'Total Paid';
  @override String get remainingBalance => 'Remaining Balance';
  @override String get amount => 'Amount';
  @override String get date => 'Date';
  @override String get dueDate => 'Due Date';
}
'''
        content = content.replace("import 'package:payme/services/pdf_generation_service.dart';", "import 'package:payme/services/pdf_generation_service.dart';\n" + fake_class)
    
    content = content.replace('PdfGenerationService()', 'PdfGenerationService(FakePdfLocalizations())')
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

