import 'package:flutter_test/flutter_test.dart';
import 'package:payme/domain/entities/invoice.dart';
import 'package:payme/domain/entities/client.dart';
import 'package:payme/domain/entities/business_settings.dart';
import 'package:payme/domain/entities/payment.dart';
import 'package:payme/domain/entities/payment_method.dart';
import 'package:payme/services/pdf_generation_service.dart';

import 'package:payme/core/pdf/pdf_localizations.dart';
class FakePdfLocalizations implements PdfLocalizations {
  @override String get billTo => 'BILL TO';
  @override String get description => 'Description';
  @override String get notes => 'Notes';
  @override String generatedBy(String name) => 'Generated by: $name';
  @override String get page => 'Page';
  @override String get of => 'of';
  @override String get totalInvoiced => 'Total Invoiced';
  @override String get totalPaid => 'Total Paid';
  @override String get remainingBalance => 'Remaining Balance';
  @override String get amount => 'Amount';
  @override String get date => 'Date';
  @override String get dueDate => 'Due Date';
  @override String get rc => 'RC';
  @override String get nif => 'NIF';
  @override String get nis => 'NIS';
  @override String get art => 'ART';
}


void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  late PdfGenerationService service;

  setUp(() {
    service = PdfGenerationService(FakePdfLocalizations());
  });

  test('generateInvoicePdf creates valid non-empty PDF bytes without logo', () async {
    final client = Client(
      id: 'c1',
      name: 'Acme Corp',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final invoice = Invoice(
      id: 'inv1',
      accountingYearId: 'y1',
      clientId: 'c1',
      invoiceNumber: 101,
      date: DateTime.now(),
      amount: 1500.0,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isDirty: false,
    );

    final settings = BusinessSettings(
      id: 1,
      currencyCode: 'USD',
      businessName: 'My Awesome Business',
    );

    final pdfBytes = await service.generateInvoicePdf(
      invoice: invoice,
      client: client,
      settings: settings,
      payments: [],
      generatedByName: 'Test User',
    );

    expect(pdfBytes, isNotEmpty);
    // PDF magic number check (starts with %PDF-)
    expect(pdfBytes.sublist(0, 5), equals([37, 80, 68, 70, 45]));
  });

  test('generateInvoicePdf layout handles extremely long strings without throwing', () async {
    final client = Client(
      id: 'c1',
      name: 'A very very very very very very very very very very very very very very very long name',
      address: 'An exceptionally exceptionally exceptionally exceptionally exceptionally exceptionally exceptionally long address that might break layout if not wrapped properly',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final invoice = Invoice(
      id: 'inv1',
      accountingYearId: 'y1',
      clientId: 'c1',
      invoiceNumber: 9999999,
      date: DateTime.now(),
      amount: 1500000.0,
      description: 'Super long description ' * 50,
      notes: 'Super long notes ' * 50,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isDirty: false,
    );

    final settings = BusinessSettings(
      id: 1,
      currencyCode: 'USD',
      businessName: 'An absolutely incredibly massively long business name to ensure text wrapping functions',
      address: 'Another incredibly long address for the business side just to be completely sure',
    );

    final payments = [
      Payment(
        id: 'p1',
        invoiceId: 'inv1',
        date: DateTime.now(),
        amount: 500000.0,
        method: PaymentMethod.bankTransfer,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        isDirty: true,
      ),
    ];

    // Should not throw any rendering/layout exceptions
    final pdfBytes = await service.generateInvoicePdf(
      invoice: invoice,
      client: client,
      settings: settings,
      payments: payments,
      logoBytes: null,
      generatedByName: 'Test User',
    );

    expect(pdfBytes, isNotEmpty);
  });

  test('generateInvoicePdf layout handles RTL (Arabic) configuration properly', () async {
    final client = Client(
      id: 'c2',
      name: 'شركة تجريبية',
      address: 'عنوان طويل جدًا لاختبار التفاف النص في تصميم الملفات بصيغة بي دي إف بشكل صحيح وبدون أي أخطاء أو قطع في النص.',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rc: 'RC123456789012345678901234567890',
      nif: 'NIF123456789012345678901234567890',
    );

    final invoice = Invoice(
      id: 'inv2',
      accountingYearId: 'y1',
      clientId: 'c2',
      invoiceNumber: 102,
      date: DateTime.now(),
      amount: 5000.0,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isDirty: false,
    );

    final settings = BusinessSettings(
      id: 1,
      currencyCode: 'DZD',
      businessName: 'شركة ممتازة',
      address: 'عنوان الشركة الطويل جدا الذي سيتم اختباره',
      languageCode: 'ar', // This triggers RTL text direction
    );

    // Should not throw any rendering/layout exceptions in RTL mode
    final pdfBytes = await service.generateInvoicePdf(
      invoice: invoice,
      client: client,
      settings: settings,
      payments: [],
      logoBytes: null,
      generatedByName: 'مستخدم تجريبي',
    );

    expect(pdfBytes, isNotEmpty);
  });

  test('generateInvoicePdf layout handles duplicate layout correctly (pw.Page + Expands)', () async {
    final client = Client(
      id: 'c1',
      name: 'Acme Corp',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final invoice = Invoice(
      id: 'inv1',
      accountingYearId: 'y1',
      clientId: 'c1',
      invoiceNumber: 101,
      date: DateTime.now(),
      amount: 1500.0,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isDirty: false,
    );

    final settings = BusinessSettings(
      id: 1,
      currencyCode: 'USD',
      businessName: 'My Awesome Business',
      defaultDocumentLayout: 'duplicate',
    );

    // Should successfully generate the duplicate layout containing two copies
    // each with its own inline footer using pw.Page and pw.Expanded.
    final pdfBytes = await service.generateInvoicePdf(
      invoice: invoice,
      client: client,
      settings: settings,
      payments: [],
      generatedByName: 'Test User',
    );

    expect(pdfBytes, isNotEmpty);
    expect(pdfBytes.sublist(0, 5), equals([37, 80, 68, 70, 45]));
  });

  test('generateInvoicePdf gracefully falls back to single layout if content is too dense', () async {
    final client = Client(
      id: 'c1',
      name: 'Acme Corp',
      address: 'Very long address ' * 10, // Exceeds 100 chars
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final invoice = Invoice(
      id: 'inv1',
      accountingYearId: 'y1',
      clientId: 'c1',
      invoiceNumber: 101,
      date: DateTime.now(),
      amount: 1500.0,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isDirty: false,
    );

    final settings = BusinessSettings(
      id: 1,
      currencyCode: 'USD',
      businessName: 'My Awesome Business',
      defaultDocumentLayout: 'duplicate',
    );

    // This should trigger the fallback to single layout because the client address is too long
    final pdfBytes = await service.generateInvoicePdf(
      invoice: invoice,
      client: client,
      settings: settings,
      payments: [],
      generatedByName: 'Test User',
    );

    expect(pdfBytes, isNotEmpty);
    expect(pdfBytes.sublist(0, 5), equals([37, 80, 68, 70, 45]));
  });
}
